build: comment out exfatprogs for now
Causes the following error atm:
Error: Unable to satisfy dependencies. Reached two conflicting assignments:
   1. exfatprogs:powerpc=1.4.2-2 is selected for install
   2. exfatprogs:powerpc is not selected for install because:
      1. udisks2:powerpc=2.10.1-12 is selected for install
      2. exfatprogs:powerpc Breaks udisks2 (< 2.11.1-2)

Comment it out and but keep it in the bullpen.

Signed-off-by: Christian Lamparter <chunkeey@gmail.com>